In [79]:
import mysql.connector
import csv
import pandas as pd
# from datetime import datetime

In [80]:
import os

In [81]:
import datetime

In [82]:
connection = mysql.connector.connect(
    host='localhost',        
    user='root',    
    password='root', 
    database='hospital_paitents'  
)

In [83]:
cursor = connection.cursor()

In [84]:
query = "SELECT * FROM Customers"
cursor.execute(query)

In [85]:
records = cursor.fetchall()


for record in records:
    print(record)

('Emily Johnson', '100001', datetime.date(2021, 3, 22), datetime.date(2023, 10, 5), 'PFIZR', 'Dr. Smith', 'CA', 'USA', 90210, datetime.date(1990, 8, 15), 'Y')
('Yuki Tanaka', '100002', datetime.date(2022, 2, 28), datetime.date(2023, 8, 14), 'MDRNA', 'Dr. Yamamoto', 'TKY', 'JPN', 100001, datetime.date(1995, 7, 7), 'Y')
('Hans Mueller', '100003', datetime.date(2022, 6, 10), datetime.date(2023, 9, 18), 'ASTRZ', 'Dr. Schmidt', 'BY', 'GER', 80331, datetime.date(1978, 11, 30), 'Y')
('Rajesh Kumar', '100004', datetime.date(2022, 1, 15), datetime.date(2023, 11, 20), 'COVAX', 'Dr. Patel', 'MH', 'IND', 400001, datetime.date(1985, 5, 10), 'Y')
('Elizabeth Taylor', '100005', datetime.date(2021, 9, 5), datetime.date(2023, 12, 1), 'ASTRZ', 'Dr. Jones', 'LDN', 'UK', 12345, datetime.date(1982, 4, 22), 'Y')
('Sarah Thompson', '100006', datetime.date(2021, 11, 11), datetime.date(2023, 10, 30), 'PFIZR', 'Dr. Brown', 'NSW', 'AUS', 2000, datetime.date(1988, 9, 25), 'Y')
('Taro Yamada', '100007', datetime.date(2022, 4, 3), datetime.date(2023, 9, 22), 'MDRNA', 'Dr. Sato', 'OSA', 'JPN', 530001, datetime.date(1992, 12, 18), 'Y')
('Michael Brown', '100008', datetime.date(2021, 7, 19), datetime.date(2023, 11, 15), 'PFIZR', 'Dr. Johnson', 'NY', 'USA', 10001, datetime.date(1987, 3, 30), 'Y')
('Anna Schmidt', '100009', datetime.date(2022, 5, 28), datetime.date(2023, 10, 12), 'ASTRZ', 'Dr. Weber', 'HE', 'GER', 60313, datetime.date(1993, 6, 5), 'Y')
('Priya Patel', '100010', datetime.date(2021, 12, 7), datetime.date(2023, 8, 30), 'COVAX', 'Dr. Sharma', 'GJ', 'IND', 380001, datetime.date(1989, 11, 22), 'Y')
('James Wilson', '100011', datetime.date(2022, 2, 14), datetime.date(2023, 9, 28), 'ASTRZ', 'Dr. Taylor', 'MAN', 'UK', 56789, datetime.date(1984, 1, 15), 'Y')
('Emma White', '100012', datetime.date(2021, 10, 20), datetime.date(2023, 12, 5), 'PFIZR', 'Dr. Davis', 'VIC', 'AUS', 3000, datetime.date(1991, 7, 8), 'Y')
('Hiroshi Suzuki', '100013', datetime.date(2022, 3, 11), datetime.date(2023, 11, 2), 'MDRNA', 'Dr. Tanaka', 'KAN', 'JPN', 220001, datetime.date(1986, 9, 14), 'Y')
('Jennifer Lee', '100014', datetime.date(2021, 8, 25), datetime.date(2023, 10, 18), 'PFIZR', 'Dr. Anderson', 'TX', 'USA', 75001, datetime.date(1994, 4, 27), 'Y')
('Thomas Becker', '100015', datetime.date(2022, 1, 30), datetime.date(2023, 9, 7), 'ASTRZ', 'Dr. M端ller', 'NW', 'GER', 40213, datetime.date(1980, 12, 3), 'Y')
('Amit Sharma', '100016', datetime.date(2021, 6, 12), datetime.date(2023, 11, 25), 'COVAX', 'Dr. Gupta', 'DL', 'IND', 110001, datetime.date(1989, 2, 18), 'Y')
('Oliver Brown', '100017', datetime.date(2022, 4, 19), datetime.date(2023, 10, 8), 'ASTRZ', 'Dr. Williams', 'ESS', 'UK', 34567, datetime.date(1993, 8, 11), 'Y')
('Sophie Martin', '100018', datetime.date(2021, 9, 30), datetime.date(2023, 12, 12), 'PFIZR', 'Dr. Wilson', 'QLD', 'AUS', 4000, datetime.date(1987, 5, 29), 'Y')
('Kenji Nakamura', '100019', datetime.date(2022, 2, 7), datetime.date(2023, 9, 14), 'MDRNA', 'Dr. Ito', 'FUK', 'JPN', 810001, datetime.date(1991, 11, 3), 'Y')
('Samantha Miller', '100020', datetime.date(2021, 11, 5), datetime.date(2023, 8, 22), 'PFIZR', 'Dr. Davis', 'FL', 'USA', 33101, datetime.date(1986, 7, 16), 'Y')
('Klaus Wagner', '100021', datetime.date(2022, 5, 14), datetime.date(2023, 10, 28), 'ASTRZ', 'Dr. Bauer', 'BW', 'GER', 70173, datetime.date(1992, 3, 25), 'Y')
('Ananya Reddy', '100022', datetime.date(2021, 8, 9), datetime.date(2023, 11, 17), 'COVAX', 'Dr. Rao', 'TN', 'IND', 600001, datetime.date(1988, 12, 30), 'Y')
('George Parker', '100023', datetime.date(2022, 1, 23), datetime.date(2023, 9, 3), 'ASTRZ', 'Dr. Harris', 'YOR', 'UK', 78901, datetime.date(1983, 6, 14), 'Y')
('Lucy Chen', '100024', datetime.date(2021, 10, 7), datetime.date(2023, 12, 19), 'PFIZR', 'Dr. Thompson', 'SA', 'AUS', 5000, datetime.date(1995, 1, 22), 'Y')
('Takashi Sato', '100025', datetime.date(2022, 3, 18), datetime.date(2023, 8, 27), 'MDRNA', 'Dr. Nakamura', 'HKD', 'JPN', 60001, datetime.date(1990, 10, 5), 'Y')
('Jessica Taylor', '100026', datetime.date(2021, 7, 2), datetime.date(2023, 11, 9), 'PFIZR', 'Dr. Wilson', 'IL', 'USA', 60601, datetime.date(1987, 4, 18), 'Y')
('Markus Schulz', '100027', datetime.date(2022, 4, 25), datetime.date(2023, 10, 14), 'ASTRZ', 'Dr. Hoffmann', 'BE', 'GER', 10115, datetime.date(1981, 9, 9), 'Y')
('Neha Gupta', '100028', datetime.date(2021, 12, 30), datetime.date(2023, 9, 25), 'COVAX', 'Dr. Chopra', 'KA', 'IND', 560001, datetime.date(1993, 7, 12), 'Y')
('William Hughes', '100029', datetime.date(2022, 2, 11), datetime.date(2023, 12, 7), 'ASTRZ', 'Dr. Evans', 'WAL', 'UK', 23456, datetime.date(1986, 11, 28), 'Y')
('Olivia Green', '100030', datetime.date(2021, 9, 16), datetime.date(2023, 8, 19), 'PFIZR', 'Dr. Clark', 'WA', 'AUS', 6000, datetime.date(1992, 5, 3), 'Y')
('Arun Gupta', '100200', datetime.date(2022, 6, 5), datetime.date(2023, 12, 15), 'COVAX', 'Dr. Reddy', 'KA', 'IND', 560001, datetime.date(1993, 8, 20), 'Y')
('Jo達o Silva', '100201', datetime.date(2022, 3, 15), datetime.date(2023, 11, 20), 'ASTRZ', 'Dr. Santos', 'SP', 'BRA', 1000000, datetime.date(1988, 9, 12), 'Y')
('Maria Oliveira', '100202', datetime.date(2021, 8, 22), datetime.date(2023, 10, 5), 'PFIZR', 'Dr. Rodrigues', 'RJ', 'BRA', 20000000, datetime.date(1995, 4, 30), 'Y')
('Carlos Ferreira', '100203', datetime.date(2022, 1, 10), datetime.date(2023, 9, 18), 'COVAX', 'Dr. Lima', 'MG', 'BRA', 30000000, datetime.date(1980, 11, 25), 'Y')
('Ana Santos', '100204', datetime.date(2021, 11, 5), datetime.date(2023, 12, 1), 'MDRNA', 'Dr. Almeida', 'RS', 'BRA', 90000000, datetime.date(1992, 7, 8), 'Y')
('Pedro Costa', '100205', datetime.date(2022, 5, 20), datetime.date(2023, 8, 14), 'ASTRZ', 'Dr. Carvalho', 'BA', 'BRA', 40000000, datetime.date(1985, 3, 17), 'Y')
('Hans M端ller', '200021', datetime.date(2023, 1, 15), datetime.date(2023, 10, 1), 'COVID', 'Dr. Schmidt', 'BW', 'DE', 70173, datetime.date(1980, 5, 10), 'Y')
('Maria Silva', '200022', datetime.date(2022, 3, 10), datetime.date(2023, 9, 20), 'FLU', 'Dr. Santos', 'SP', 'BR', 1000, datetime.date(1965, 7, 25), 'Y')
('Emily Johnson', '200023', datetime.date(2023, 7, 21), None, 'HEPB', 'Dr. Clark', 'ENG', 'GB', 10001, datetime.date(1985, 9, 14), 'Y')
('Rajesh Kumar', '200024', datetime.date(2021, 11, 8), datetime.date(2022, 12, 5), 'COVID', 'Dr. Gupta', 'MH', 'IN', 400001, datetime.date(1995, 11, 3), 'N')
('Sofia Costa', '200025', datetime.date(2020, 5, 15), datetime.date(2023, 6, 18), 'FLU', 'Dr. Pereira', 'RJ', 'BR', 20000, datetime.date(1978, 2, 28), 'Y')
('Hans M端ller', '200031', datetime.date(2023, 1, 15), datetime.date(2023, 10, 1), 'COVID', 'Dr. Schmidt', 'BW', 'GER', 70173, datetime.date(1980, 5, 10), 'Y')
('Maria Silva', '200032', datetime.date(2022, 3, 10), datetime.date(2023, 9, 20), 'FLU', 'Dr. Santos', 'SP', 'BRA', 1000, datetime.date(1965, 7, 25), 'Y')
('Emily Johnson', '200033', datetime.date(2023, 7, 21), None, 'HEPB', 'Dr. Clark', 'ENG', 'UK', 10001, datetime.date(1985, 9, 14), 'Y')
('Rajesh Kumar', '200034', datetime.date(2021, 11, 8), datetime.date(2022, 12, 5), 'COVID', 'Dr. Gupta', 'MH', 'IND', 400001, datetime.date(1995, 11, 3), 'N')
('Sofia Tanaka', '200035', datetime.date(2020, 5, 15), datetime.date(2023, 6, 18), 'FLU', 'Dr. Watanabe', 'TK', 'JPN', 99, datetime.date(1978, 2, 28), 'Y')

In [86]:
csv_file_name = 'customers_data.csv'

In [87]:
with open(csv_file_name, mode='w', newline='') as file:
    writer = csv.writer(file)
    
    
    writer.writerow([i[0] for i in cursor.description]) 

   
    writer.writerows(records)

In [88]:
df = pd.read_csv('customers_data.csv', encoding='ISO-8859-1')

In [89]:
df

,Customer_Name,Customer_Id,Open_Date,Last_Consulted_Date,Vaccination_Type,Doctor_Consulted,State,Country,Post_Code,Date_of_Birth,Active_Customer
0,Emily Johnson,100001,2021-03-22,2023-10-05,PFIZR,Dr. Smith,CA,USA,90210,1990-08-15,Y
1,Yuki Tanaka,100002,2022-02-28,2023-08-14,MDRNA,Dr. Yamamoto,TKY,JPN,100001,1995-07-07,Y
2,Hans Mueller,100003,2022-06-10,2023-09-18,ASTRZ,Dr. Schmidt,BY,GER,80331,1978-11-30,Y
3,Rajesh Kumar,100004,2022-01-15,2023-11-20,COVAX,Dr. Patel,MH,IND,400001,1985-05-10,Y
4,Elizabeth Taylor,100005,2021-09-05,2023-12-01,ASTRZ,Dr. Jones,LDN,UK,12345,1982-04-22,Y
5,Sarah Thompson,100006,2021-11-11,2023-10-30,PFIZR,Dr. Brown,NSW,AUS,2000,1988-09-25,Y
6,Taro Yamada,100007,2022-04-03,2023-09-22,MDRNA,Dr. Sato,OSA,JPN,530001,1992-12-18,Y
7,Michael Brown,100008,2021-07-19,2023-11-15,PFIZR,Dr. Johnson,NY,USA,10001,1987-03-30,Y
8,Anna Schmidt,100009,2022-05-28,2023-10-12,ASTRZ,Dr. Weber,HE,GER,60313,1993-06-05,Y
9,Priya Patel,100010,2021-12-07,2023-08-30,COVAX,Dr. Sharma,GJ,IND,380001,1989-11-22,Y
10,James Wilson,100011,2022-02-14,2023-09-28,ASTRZ,Dr. Taylor,MAN,UK,56789,1984-01-15,Y
11,Emma White,100012,2021-10-20,2023-12-05,PFIZR,Dr. Davis,VIC,AUS,3000,1991-07-08,Y
12,Hiroshi Suzuki,100013,2022-03-11,2023-11-02,MDRNA,Dr. Tanaka,KAN,JPN,220001,1986-09-14,Y
13,Jennifer Lee,100014,2021-08-25,2023-10-18,PFIZR,Dr. Anderson,TX,USA,75001,1994-04-27,Y
14,Thomas Becker,100015,2022-01-30,2023-09-07,ASTRZ,Dr. M端ller,NW,GER,40213,1980-12-03,Y
15,Amit Sharma,100016,2021-06-12,2023-11-25,COVAX,Dr. Gupta,DL,IND,110001,1989-02-18,Y
16,Oliver Brown,100017,2022-04-19,2023-10-08,ASTRZ,Dr. Williams,ESS,UK,34567,1993-08-11,Y
17,Sophie Martin,100018,2021-09-30,2023-12-12,PFIZR,Dr. Wilson,QLD,AUS,4000,1987-05-29,Y
18,Kenji Nakamura,100019,2022-02-07,2023-09-14,MDRNA,Dr. Ito,FUK,JPN,810001,1991-11-03,Y
19,Samantha Miller,100020,2021-11-05,2023-08-22,PFIZR,Dr. Davis,FL,USA,33101,1986-07-16,Y
20,Klaus Wagner,100021,2022-05-14,2023-10-28,ASTRZ,Dr. Bauer,BW,GER,70173,1992-03-25,Y
21,Ananya Reddy,100022,2021-08-09,2023-11-17,COVAX,Dr. Rao,TN,IND,600001,1988-12-30,Y
22,George Parker,100023,2022-01-23,2023-09-03,ASTRZ,Dr. Harris,YOR,UK,78901,1983-06-14,Y
23,Lucy Chen,100024,2021-10-07,2023-12-19,PFIZR,Dr. Thompson,SA,AUS,5000,1995-01-22,Y
24,Takashi Sato,100025,2022-03-18,2023-08-27,MDRNA,Dr. Nakamura,HKD,JPN,60001,1990-10-05,Y
25,Jessica Taylor,100026,2021-07-02,2023-11-09,PFIZR,Dr. Wilson,IL,USA,60601,1987-04-18,Y
26,Markus Schulz,100027,2022-04-25,2023-10-14,ASTRZ,Dr. Hoffmann,BE,GER,10115,1981-09-09,Y
27,Neha Gupta,100028,2021-12-30,2023-09-25,COVAX,Dr. Chopra,KA,IND,560001,1993-07-12,Y
28,William Hughes,100029,2022-02-11,2023-12-07,ASTRZ,Dr. Evans,WAL,UK,23456,1986-11-28,Y
29,Olivia Green,100030,2021-09-16,2023-08-19,PFIZR,Dr. Clark,WA,AUS,6000,1992-05-03,Y
30,Arun Gupta,100200,2022-06-05,2023-12-15,COVAX,Dr. Reddy,KA,IND,560001,1993-08-20,Y
31,Jo達o Silva,100201,2022-03-15,2023-11-20,ASTRZ,Dr. Santos,SP,BRA,1000000,1988-09-12,Y
32,Maria Oliveira,100202,2021-08-22,2023-10-05,PFIZR,Dr. Rodrigues,RJ,BRA,20000000,1995-04-30,Y
33,Carlos Ferreira,100203,2022-01-10,2023-09-18,COVAX,Dr. Lima,MG,BRA,30000000,1980-11-25,Y
34,Ana Santos,100204,2021-11-05,2023-12-01,MDRNA,Dr. Almeida,RS,BRA,90000000,1992-07-08,Y
35,Pedro Costa,100205,2022-05-20,2023-08-14,ASTRZ,Dr. Carvalho,BA,BRA,40000000,1985-03-17,Y
36,Hans M端ller,200021,2023-01-15,2023-10-01,COVID,Dr. Schmidt,BW,DE,70173,1980-05-10,Y
37,Maria Silva,200022,2022-03-10,2023-09-20,FLU,Dr. Santos,SP,BR,1000,1965-07-25,Y
38,Emily Johnson,200023,2023-07-21,NaN,HEPB,Dr. Clark,ENG,GB,10001,1985-09-14,Y
39,Rajesh Kumar,200024,2021-11-08,2022-12-05,COVID,Dr. Gupta,MH,IN,400001,1995-11-03,N
40,Sofia Costa,200025,2020-05-15,2023-06-18,FLU,Dr. Pereira,RJ,BR,20000,1978-02-28,Y
41,Hans M端ller,200031,2023-01-15,2023-10-01,COVID,Dr. Schmidt,BW,GER,70173,1980-05-10,Y
42,Maria Silva,200032,2022-03-10,2023-09-20,FLU,Dr. Santos,SP,BRA,1000,1965-07-25,Y
43,Emily Johnson,200033,2023-07-21,NaN,HEPB,Dr. Clark,ENG,UK,10001,1985-09-14,Y
44,Rajesh Kumar,200034,2021-11-08,2022-12-05,COVID,Dr. Gupta,MH,IND,400001,1995-11-03,N
45,Sofia Tanaka,200035,2020-05-15,2023-06-18,FLU,Dr. Watanabe,TK,JPN,99,1978-02-28,Y

In [90]:
grouped = df.groupby('Country')

In [91]:
timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

In [92]:
for country, group in grouped:
   
    filename = f'customers_{country}_{timestamp}.csv'
    
    group.to_csv(filename, index=False)
    print(f'Saved {filename}')

Saved customers_AUS_20241009_230109.csv
Saved customers_BR_20241009_230109.csv
Saved customers_BRA_20241009_230109.csv
Saved customers_DE_20241009_230109.csv
Saved customers_GB_20241009_230109.csv
Saved customers_GER_20241009_230109.csv
Saved customers_IN_20241009_230109.csv
Saved customers_IND_20241009_230109.csv
Saved customers_JPN_20241009_230109.csv
Saved customers_UK_20241009_230109.csv
Saved customers_USA_20241009_230109.csv

In [93]:
output_directory = r'C:\Users\Ashmit\Desktop\etlnew\country'

In [94]:
os.makedirs(output_directory, exist_ok=True)

In [95]:
for country, group in grouped:
    filename = f'customers_{country}_{timestamp}.csv'
    
    file_path = os.path.join(output_directory, filename)
    
    group.to_csv(file_path, index=False)
    print(f'Saved {file_path}')

Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_AUS_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_BR_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_BRA_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_DE_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_GB_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_GER_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_IN_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_IND_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_JPN_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_UK_20241009_230109.csv
Saved C:\Users\Ashmit\Desktop\etlnew\country\customers_USA_20241009_230109.csv